nodeSelector: {}
securityContext: {}
podSecurityContext:
  runAsUser: 0
image:
  repository: jenkins/jenkins
  pullPolicy: IfNotPresent
  tag: lts-jdk17
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: ClusterIP
  port: 8080
nfs:
  enabled: false
  storage: 20Gi
  path: /nfs_share/jenkins
  server: 192.168.16.3